### ISSUE TITLE
Token renewal

### ISSUE THREAD

**Issue by robbanl** [DarkGhostHunter/Captchavel#16]
Hello!

Using auto-mode but from what I can see, the token is not refreshed after 2 minutes (when it expires according to Google) :-O 

I'm about to write a small js string that will refresh the token automatically to see if it helps, or have I missunderstood something? :)

Thanks!

**Comment by DarkGhostHunter** [comment]
Indeed, [the token expires and is not refreshed automatically](https://developers.google.com/recaptcha/docs/verify#token_restrictions), not by Google or the package script.

I think we can wrap the `forEach()` part of the Array into a function that runs an 120 second interval.

**Comment by DarkGhostHunter** [comment]
Fixed in newest version.
