### ISSUE TITLE
Errors  when trying to install the package on Laravel ^7.0

### ISSUE THREAD

**Issue by shalien** [DarkGhostHunter/Captchavel#17]
When trying to install the package on a fresh Laravel 7.0 install the installation fails with the following message :
    - Installation request for laravel/framework (locked at v7.0.7, required as ^7.0) -> satisfiable by laravel/framework[v7.0.7].
    - darkghosthunter/captchavel v2.0.0 requires illuminate/view 6.* -> satisfiable by illuminate/view[6.x-dev].
    - darkghosthunter/captchavel v2.0.1 requires illuminate/view 6.* -> satisfiable by illuminate/view[6.x-dev].
    - Conclusion: don't install illuminate/view 6.x-dev
    - Installation request for darkghosthunter/captchavel ^2.0 -> satisfiable by darkghosthunter/captchavel[v2.0.0, v2.0.1].

**Comment by DarkGhostHunter** [comment]
I just released version 2.1.0 with Laravel 7 compatibility.
