### ISSUE TITLE
when activate CAPTCHAVEL_LOCAL=true error on The reCAPTCHA token received is invalid 

### ISSUE THREAD

**Issue by xhava** [DarkGhostHunter/Captchavel#23]
when i activate the local enviroment the error The reCAPTCHA token received is invalid  is shown.

**Comment by DarkGhostHunter** [comment]
Can you give more details?

**Comment by DarkGhostHunter** [comment]
Remember to set your reCAPATCHA site keys and secret.

Closed pending inactivity.
