### ISSUE TITLE
The reCAPTCHA token received is invalid

### ISSUE THREAD

**Issue by bradsapp** [DarkGhostHunter/Captchavel#29]
Why do I get the following error from time to time? Are these bots submitting the form? The form works for me when I submit myself, but every now and then I get "The reCAPTCHA token received is invalid".

Below is part of the response. Let me know if you need the rest of the response from Laravel.

Thank you for your hard work and help.

```
"class": "DarkGhostHunter\\Captchavel\\Exceptions\\InvalidRecaptchaException",
    "message": "The reCAPTCHA token received is invalid",
    "code": 0,
```

**Comment by DarkGhostHunter** [comment]
Most of the time is because the JavaScript is not loaded in time and the request is sent without the token. Other times, is because the token expires and must be manually renewed.

**Comment by bradsapp** [comment]
Thanks for the response. What code can I add to catch this and redirect the user back to the contact page? I don't want to miss out on any communications from the contact form.

**Comment by DarkGhostHunter** [comment]
It will depend on your application. I would suggest generating the token every minute through JavaScript.
