### ISSUE TITLE
Update package to support Laravel 8

### ISSUE THREAD

**Issue by xorock** [DarkGhostHunter/Captchavel#31]
Can you please raise the minimum version to support both v 7 and 8?

**Comment by DarkGhostHunter** [comment]
I'll do it once it passes Laravel 8 test. Shouldn't have any problems.

**Comment by Sindoweb** [comment]
Any news on this?

**Comment by orthosie** [comment]
Any updates on this? We have submitted a pull request too updating the composer file, but not sure whether that is enough.

**Comment by DarkGhostHunter** [comment]
Updated to Laravel 8.0, and PHP 8.0.
