### ISSUE TITLE
Class 'DarkGhostHunter\Captchavel\ReCaptcha' not found ?

### ISSUE THREAD

**Issue by EG-Mohamed** [DarkGhostHunter/Captchavel#51]
Hello, thanks for this packing but am facing a problem 
```
Class 'DarkGhostHunter\Captchavel\ReCaptcha' not found
```
Even PhpStorm didn't recognize packing 

![image](https://user-images.githubusercontent.com/23424932/148839880-7dce0f8e-cf1e-4166-b791-519cfd1742e8.png)

**Comment by EG-Mohamed** [comment]
Laravel version : v8.75.0
Php Version : 7.4.15

**Comment by DarkGhostHunter** [comment]
PR a fix, AFK until next month.

**Comment by Temepest74** [comment]
for anyone who stumbles upon this. I don't have any clue why this is happening, or how to solve it.
But I know that if you use [this](https://github.com/barryvdh/laravel-ide-helper), you will be able to find that class.
