### ISSUE TITLE
Laravel 6.x support?

### ISSUE THREAD

**Issue by BrekiTomasson** [DarkGhostHunter/Captchavel#9]
Any news on when you'll be supporting Laravel 6.x? This package is currently stopping my upgrade to 6.x. Looking at the code, it doesn't look like there anything in particular that would stop you from just changing the dependencies and allow 6.x as well.

**Comment by DarkGhostHunter** [comment]
I'm working on it.

**Comment by DarkGhostHunter** [comment]
Done!
